app_port: "8080"
log_level: "info"

db:
  host: "db"
  port: 5432
  user: "user"
  password: "password"
  name: "subscriptions_db"
  dsn: "postgres://user:password@db:5432/subscriptions_db?sslmode=disable"